version: '3'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./gateway:/usr/src/app
    networks:
      - app-network
    links:
      - users

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./users:/usr/src/app
    networks:
      - app-network
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: longnight
      MYSQL_USER: mysql
      MYSQL_PASSWORD: pass123
    depends_on:      
      - db

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./products:/usr/src/app
    networks:
      - app-network
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: longnight
      MYSQL_USER: mysql
      MYSQL_PASSWORD: pass123
    depends_on:      
      - db

  reviews:
    build:
      context: ./reviews
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./reviews:/usr/src/app
    networks:
      - app-network
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: longnight
      MYSQL_USER: mysql
      MYSQL_PASSWORD: pass123
    depends_on:      
      - db
  
  barter:
    build:
      context: ./barter
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    volumes:
      - ./barter:/usr/src/app
    networks:
      - app-network
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: longnight
      MYSQL_USER: mysql
      MYSQL_PASSWORD: pass123
    depends_on:      
      - db

  db:
    build: ./db
    environment:
      MYSQL_DATABASE: longnight
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_USER: mysql
      MYSQL_PASSWORD: pass123
      DATABASE_HOST: db
    networks:
      - app-network
  
  react:
    build: ./barter-app
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./barter-app/src:/usr/src/app/src
      - ./barter-app/public:/usr/src/app/public
    networks:
      - app-network  
    
networks:
  app-network:
    driver: bridge
